#!/bin/bash
# Bilder in jpg convertieren

find -name "*.svg" -o -name "*.SVG" | while read i;
do 
	echo "Diese Datei $i wird Dark Theme"
	fname=$( basename "$i")
#	echo "hat den Namen: $fname"
	fdir=$( dirname "$i")
#	echo "und steht im Verzeichnis: ${fdir##*/}"
	#inkscape -f "$i" -e "${i%.*}.png"
	sed -i -e 's/#4d4d4d/#f2f2f2/g' "$i"
	sed -i -e 's/#eff0f1/#31363b/g' "$i"
	sed -i -e 's/#fcfcfc/#4f575f/g' "$i"
	#convert "$i" -quality 75 "$i"
done 
